### ISSUE TITLE
Add `append`, `prepend`, `pop`, and `shift` methods

### ISSUE THREAD

**Issue by elpete** [elpete/CFCollection#7]
Add the following array manipulation methods

* `append`
    * Add an item to the end of the collection.
* `prepend`
    * Add an item to the beginning of the collection.
* `pop`
   * Remove an item from the end of the collection and return it.
* `shift`
    * Remove an item from the beginning of the collection and return it

**Comment by jasonbrookins** [comment]
I wouldn't mind taking a look at this; I used CFCollection a long time ago, so it's time to give back.  What do I need to do a PR for this?

**Comment by elpete** [comment]
Awesome! I think one test for each of the new methods.  I can help you get started with those if you need.  You can ping me on the CFML Slack.

**Comment by jasonbrookins** [comment]
@elpete :  Can you open this back up as "contributions: up for grabs"? I got sucked into a bunch of stuff for the Lucee folks, and I don't think I'll have the time to get to this anytime soon.

**Comment by elpete** [comment]
No worries!

**Comment by elpete** [comment]
Closed by #15
